autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
      - 'docs/**/*'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
      - '/hotfix\/.+/'
      - '/bug\/.+/'
    title:
      - '/fix/i'
      - '/bug/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
      - '/story\/.+/'
      - '/enhance\/.+/'
    body:
      - '/UGC-[0-9]{1,4}/'

name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'story'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'hotfix'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'maintenance'
      - 'dependencies'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '⚡ Performance'
    labels:
      - 'performance'
      - 'perf'
  - title: '🔒 Security'
    labels:
      - 'security'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
      - 'story'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'hotfix'
      - 'maintenance'
      - 'docs'
      - 'documentation'
      - 'dependencies'
      - 'security'
  default: patch

template: |
  ## What's Changed

  $CHANGES

  ## 👥 Contributors

  $CONTRIBUTORS

  ## 📝 Notes

  For the full list of changes, see the [comparison view](https://github.com/pal-paul/pal-nas-media-uploader/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION).
